### ISSUE TITLE
evidence to support "unmatched video quality and latency" statement

### ISSUE THREAD

**Issue by jeffreyyoung** [ianramzy/decentralized-video-chat#19]
The app looks really awesome and I love the clean UI!   My understanding is various other video chat apps are also built on web rtc, so I would think they would also have the same video quality and latency as this app.   Can you explain technically why this service has better video quality than other video chat apps?  Or maybe change the headline to be  "High quality, easy to use peer to peer browser video calling platform"?

**Comment by ianramzy** [comment]
Thanks Jeffrey! Very few if any mainstream video calling apps will leverage peer to peer for their video streams entirely. This is the main benefit, the other properties that make this "highest quality" are the fact that it uses modern codecs and auto-scaling for video quality. I do agree the claim is very much an attention grab and perhaps an oversell. I guess a better title would be unbeatable, no unmatched.
