### ISSUE TITLE
Easy questions about the project

### ISSUE THREAD

**Issue by gerald-dotcom** [ianramzy/decentralized-video-chat#22]
Did you start this own? If yes, How long did it take for you to build this from up-ground?

**Comment by muffledMitosis** [comment]
You could take a look at the commits to get a basic idea for now, they have a time associated with them :)

https://github.com/ianramzy/decentralized-video-chat/commits/master?after=6101706fa742015e6b9d94b93c58dbaf2fab3eeb+104

You'll see the initial commit at the bottom of the page. :)

**Comment by ianramzy** [comment]
About 3 weeks, commit history is a good way to see the progression.

**Comment by AdrianKujawski** [comment]
What is your experience in developing applications with similar tools / technologies?

**Comment by ianramzy** [comment]
I am a software engineer of 3 years and I have had little prior knowledge. Feel free to ask more questions on our communitie's Gitter https://gitter.im/zipcall
