### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by tobidwest** [ianramzy/decentralized-video-chat#23]
I cloned the repository and changed the .env file accordingly. However when trying to access I get the error:
`Forbidden
You do not have permission to access this document.`

Also, does Twilio charge anything when using your selfhosted Zipcall?

**Comment by ianramzy** [comment]
Chrome 47 and higher block non-TLS access to WebRTC. Try accessing with HTTPS.

**Comment by tobidwest** [comment]
Thanks for reaching back!

However, this does not solve the problem, same error code 403.

**Comment by Chaphasilor** [comment]
Does the error occur when starting the server or when trying to access the website?

Also to answer your other question, twilio offers a free trail (no credit card required) but after that it will cost.  
However, we are looking into options for self-hosting a twilio alternative :)

**Comment by tobidwest** [comment]
It occurs when accessing the website

I could not run "npm install" - we're on shared hosting, so I cannot run
commands. However, I think every dependency needed is installed.

Perhaps you could make a ready release available in the future which can be
uploaded via ftp so that only changing the Twilio credentials is needed?

**Comment by Chaphasilor** [comment]
> `Forbidden You do not have permission to access this document.`

I honestly don't think this error is related to zipcall, but to your server environment. check if the server is running on a free port.

But anyway, here you have my local build, running with no issues. Just insert the twilio keys and you're good to go :)

[zipcall.zip](https://github.com/ianramzy/decentralized-video-chat/files/4482212/zipcall.zip)

**Comment by tobidwest** [comment]
Thank you very much :)

Then I'll stop bothering you and try to figure it out myself, since the
issue is related to my end. I'll probably check the logs later.

Please feel free to close the issue. Unfortunately, I can't right now, as
I'm answerting from my emal client.

Stay healthy!

**Comment by tobidwest** [comment]
The error logs say "RSA certificate configured does NOT include an ID which
matches the server name".

The issue seems to be related to our server, right?

>

**Comment by Chaphasilor** [comment]
> The issue seems to be related to our server, right?

Yes and no. This might be an SSL error preventing the server from serving the site over `https`.
You should try setting up a proper SSL certificate first before using the server, or, if you quickly want to test if the app works, you might turn off https redirections, then use `http` to open the page and then mark the site as secure using your browser's flags. Not sure if this works though...
