### ISSUE TITLE
This is not free!

### ISSUE THREAD

**Issue by c16a** [ianramzy/decentralized-video-chat#24]
Does requiring a Twilio account categorise at being free, forget open source?

**Comment by ianramzy** [comment]
You can get a free trial from Twillio that comes with more than enough credits to test 1000's of calls without any money. It is free :)

**Comment by ianramzy** [comment]
Link to get free trial account: https://www.twilio.com/try-twilio

**Comment by JanOwiesniak** [comment]
Have to agree with @c16a [Twillio will cost you money sooner or later](https://www.twilio.com/video/pricing). You should mention those potential costs in the README.

**Comment by hialvaro** [comment]
I think he might be referring to "Free as in freedom"?

**Comment by scottrotton** [comment]
Also have to agree, not free, maybe free to trial you should update the title.

**Comment by hirako2000** [comment]
Or better, get rid of Twillio.

**Comment by Chaphasilor** [comment]
Does socket.io offer a`TURN`server?

**Comment by hirako2000** [comment]
Nope. But there are open source solutions for TURN and TUN as well.

**Comment by JanOwiesniak** [comment]
You could checkout this project for example:

https://github.com/coturn/coturn

**Comment by Chaphasilor** [comment]
Yeah I looked at coturn already :)

I was just confused what this had to do with Socket.io...

**Comment by hirako2000** [comment]
sorry ignore my own confusion. I thought it was only socket needs. (coturn looks great)
