### ISSUE TITLE
How is this decentralized?

### ISSUE THREAD

**Issue by gerroon** [ianramzy/decentralized-video-chat#29]
The doc says it is decentralized but using Twilio STUN/TURN infrastructure. Given that there is no guarantee that the connections wont go through the Twilio's network, the claim should be toned down in  my view.

You should at least give people a chance to use their own TURN servers.

**Comment by Chaphasilor** [comment]
You are right and we are working on integrating an open-source TURN server to use with Zipcall :)

**Comment by g0ne150** [comment]
Hi, check out this https://github.com/ianramzy/decentralized-video-chat/pull/33

**Comment by JayWelsh** [comment]
Am I missing something, or does this video chat, by design, require a centralised server to handle things such as socket connections & message relaying? Why is it that way?

**Comment by Chaphasilor** [comment]
@JayWelsh this is because it is very common for WebRTC connections to fail because of firewall/NAT restrictions. A STUN server fix this by resolving the IPs and relaying the traffic. Without, many calls would fail to connect.

**Comment by JayWelsh** [comment]
@Chaphasilor I am not talking about the STUN servers, I am talking about the server.js file which seems to be an additional centralised dependency beyond just the STUN servers (i.e. the clients do not seem to be handling the STUN server related activity directly).

**Comment by Chaphasilor** [comment]
Ahh I see what you mean. This is so we can manage rooms. You couldn't find the other party without the server, because the stations simply don't know each other. And including a target IP or something similar in the shared link would be a security issue.

Normally, decentralized means that every station knows everything, or that you require access to all stations to know everything. Here the connection and data transfer is dezentralized, but connection management is handled my a central entity.

**Comment by JayWelsh** [comment]
@Chaphasilor is the only reason why a centralised server is being used to conceal the IP address? Does the client-side application never gain knowledge of the IP address of the peer they are connecting to? If so, how is the data transfer decentralised or peer-to-peer? If the server ultimately returns the IP address of the peer to the frontend, then whether or not the IP address is in the shared link seems relatively inconsequential from a security perspective. I would like to think about how to increase the decentralisation of this application, perhaps using something like Ethereum, I appreciate you taking the time to respond. <3

**Comment by Chaphasilor** [comment]
Honestly, those are questions for @ianramzy :)

**Comment by ianramzy** [comment]
@JayWelsh we could implement a lighterweight backend for just serving static files, but there needs to be what's called a 'signalling server' in the startup/connection of the two callers. I was thinking about using a firebase implementation as well. I have worked with blockchain in the past and its a pain to use, and there are a lot more mission-critical items to fix for now. :)

**Comment by JayWelsh** [comment]
@ianramzy Thanks for the response, I am considering integrating this into a decentralised application which runs on the Ethereum Virtual Machine, but it would need to be decentralised in order for me to do that. The homepage of zipcall.io says "No Server Needed" but what is being said in this thread seems to be in contravention to that. I am happy to do the blockchain-related work, I don't find it to be a pain and am quite comfortable using Ethereum. Firebase would definitely not be the right direction to head in if one intends to call this decentralised. Is there any reason why the creator of the call can not also play the role of being the "signalling server" from within the browser? :)

**Comment by ianramzy** [comment]
because the creator of the call has no way of signalling the call data to
the other caller until they are connected. If you want to see what the
signalling server has to do, then a quick search of 'webrtc signalling
server' should give ample results.

**Comment by JayWelsh** [comment]
Thanks @ianramzy , will take a look into it.

**Comment by Chaphasilor** [comment]
@JayWelsh any progress? :)  
If yes, you could open a PR or a separate issue!

**Comment by pj8912** [comment]
Decentralized webrtc p2p network using kademlia

http://www.scs.stanford.edu/20sp-cs244b/projects/WebRTC%20P2P%20network.pdf

There are already lots of implementation of kademlia which you use it for signaling on a p2p network according to this paper. 

I don't think that is a big issue to be solved and does not contribute much in terms of decentralization. 

There is always stun/turn servers that are heavily centralized which is the main part of webrtc based application used for address lookup and transfer of media.
