### ISSUE TITLE
How can I figure out what specs I need in order to support 10 / 100 / 1000 users ONLINE?

### ISSUE THREAD

**Issue by inglesuniversal** [ianramzy/decentralized-video-chat#37]
What is the rough figure you have tested in the past of MAX simultaneous connections?

Thanks

Hugo

**Comment by Chaphasilor** [comment]
I guess the server should handle 1000 users without any problems. Currently there are around 25k users using the public server on Heroku, which is probably using the hobby dyno type.

The peer to peer nature makes scaling really cheap and easy!
