### ISSUE TITLE
What is the girl in the video saying?

### ISSUE THREAD

**Issue by dynect** [ianramzy/decentralized-video-chat#38]
I was trying to figure it out by trying to read her lips. My guess is she says 

> Computer ... (something) video is so cool.

![](https://github.com/ianramzy/decentralized-video-chat/raw/master/public/images/preview.gif)

Does anyone know?

**Comment by Chaphasilor** [comment]
I guess @ianramzy knows...

**Comment by ianramzy** [comment]
Haha no clue sorry
