### ISSUE TITLE
Verify Phone Number error Account is inactive

### ISSUE THREAD

**Issue by fullmap** [ianramzy/decentralized-video-chat#50]
when Sign up for free twilio account https://www.twilio.com/login,Verify Phone Number error,show Account is inactive. come from china.using mobile number.

**Comment by ianramzy** [comment]
Not sure, sorry. This is an issue with Twillio and not Zipcall. I can reccomend getting a free disposable phone number to use instead, try an app like TextNow for getting a phone number.
