### ISSUE TITLE
Which License? 

### ISSUE THREAD

**Issue by reed-jones** [ianramzy/decentralized-video-chat#54]
in the LICENSE file I see `Creative Commons Attribution-NonCommercial 4.0 International Public License` which I suspect is the one you meant? in package.json however the license is marked as ISC

**Comment by sam-cross** [comment]
ISC is the default NPM licence. So I assume this is licenced under CC.

**Comment by reed-jones** [comment]
woops, didn't mean to close. sorry. I assumed that too, but just thought if that was the case we can update package.json

**Comment by ianramzy** [comment]
Fixed.
