### ISSUE TITLE
Features Request : Is it possible to record the video streams in each room as separate folder?

### ISSUE THREAD

**Issue by TechRova** [ianramzy/decentralized-video-chat#64]
I need recording of call

Like let the room name is **BusinessCall**

I need to store the video streams screen shares like 

Create folder named **BusinessCall**
Save videos as
User1.mp4
User2.mp4
User3.mp4
Audiouser.mp4
Screenshare.mp4
Chats.json 

Is that possible?

Or guide me to implement on my own?

**Comment by Chaphasilor** [comment]
Zipcall runs in the browser. It's a website.

Websites don't have direct access to the file system and therefore can't create files or folders. Best they can do is offer a download for a single file or archive.

Recording the video streams is also not feasable without files system access.

So no, there's no way we can implement what you are trying to do.

I theory you might be able to use something like puppeteer to extract the different video streams and save them to different files, but that would be a lot of work and far from convenient...

**Comment by TechRova** [comment]
> Zipcall runs in the browser. It's a website.

So the Video streams dont to the hosted server . Just directly goes to the users. The server just as a guide only ?

Am I right ?

**Comment by Chaphasilor** [comment]
> So the Video streams dont to the hosted server . Just directly goes to the users. The server just as a guide only ?

Yes, that is what 'decentralized' means in this case. Thw video is transmitted peer-to-peer, the server only manages the rooms :)

**Comment by TechRova** [comment]
> > So the Video streams dont to the hosted server . Just directly goes to the users. The server just as a guide only ?
> 
> Yes, that is what 'decentralized' means in this case. The video is transmitted peer-to-peer, the server only manages the rooms :)

Ohh ok . Can you guide me to catch this streams by joining as another user   in the room and record them ... pls

**Comment by Chaphasilor** [comment]
Have you used puppeteer or selenium before? If not, you should become familiar with one of them before attempting this.

For now, the easiest solution would be to use a software like OBS and record the different sections of the webpage :)

**Comment by TechRova** [comment]
> Zipcall runs in the browser. It's a website.
> 
> Websites don't have direct access to the file system and therefore can't create files or folders. Best they can do is offer a download for a single file or archive.
> 
> Recording the video streams is also not feasable without files system access.
> 
> So no, there's no way we can implement what you are trying to do.
> 
> I theory you might be able to use something like puppeteer to extract the different video streams and save them to different files, but that would be a lot of work and far from convenient...

Do  Zipcall support adaptive streaming ?

**Comment by Chaphasilor** [comment]
It supports WebRTC auto-scaling, if that's what you want to know...

**Comment by TechRova** [comment]
> It supports WebRTC auto-scaling, if that's what you want to know...

why the variables names and function names in **/public/js/landing.js** are just single alphabets ? why dont they have proper names ?

**Comment by Chaphasilor** [comment]
It's generated & minified code. You'd have to ask @ianramzy how it ended up there...

However, this doesn't really have much to do with your issue anymore, does it?  
If not, I'd like to close this issue :)

**Comment by ianramzy** [comment]
Yep its minified at @TechRova

**Comment by TechRova** [comment]
> Yep its minified at @TechRova

Ooh will you please provide the full original code?
