### ISSUE TITLE
Video Camera not opening in live server 

### ISSUE THREAD

**Issue by us4group** [ianramzy/decentralized-video-chat#69]
Hi sir,

Thank you for your code . i have  configure it for testing in my AWS server . everything is running fine in my local server, but unable to open video cam on my live server . 

Please help me 
http://13.233.110.144:3000/join/OldGhost

console error : 
Uncaught TypeError: navigator.mediaDevices is undefined
    requestMediaStream http://13.233.110.144:3000/js/chat.js:45
    startUp http://13.233.110.144:3000/js/chat.js:873
    <anonymous> http://13.233.110.144:3000/js/chat.js:944

**Comment by Chaphasilor** [comment]
Your site needs to be served over **https**, not http. Without https (called *secure context*), browsers won't allow access to certain browser APIs, one of them being `navigator.mediaDevices` :)
