### ISSUE TITLE
Mobile layout

### ISSUE THREAD

**Issue by Chaphasilor** [ianramzy/decentralized-video-chat#7]
Add new CSS to support mobile devices in portrait mode.  
Maybe also make the buttons a bit larger when in landscape mode.

**Comment by Chaphasilor** [comment]
The basic layout is done as of e678d1570ff7c153ee6a2a4b3664d742df1900c8

**Comment by Chaphasilor** [comment]
TODO:  
- [ ] fix fading the controls in and out with proper styling (I implemented a quick fix in 98f96d012b3b576b89917a3af5fe87882bd1f95b, couldn't test it out yet though)
- [ ] fix positioning of the local video  
  currently it can't be dragged around

**Comment by ianramzy** [comment]
Android support has been added and merged in now. 
TODO:
- [ ]  Figure out how to play two video simultaneously on iOS
- [ ] Detect if opened in one of the crappy built-in browsers (such as the browser built into FB, Messanger, Snapchat) and tell them to open in a full browser
- [ ] On iOS WebRTC is only supported on Safari, so for iOS users using other browsers (such as chrome), need to display a message for them to open in safari

**Comment by Chaphasilor** [comment]
[in here](https://stackoverflow.com/questions/36652614/two-html5-videos-playing-simultaneously-in-ios-safari) it says that muting audio on the second video might help, we could try muting audio for the local video, we don't need it anyways?

**Comment by inglesuniversal** [comment]
Very promising project!

Best regards

**Comment by ianramzy** [comment]
It appears adding the parameter  playsinline gets both videos to play at the same time not in fullscreen i.e
`<video id="remote-video" autoplay playsinline></video>`

**Comment by Chaphasilor** [comment]
> `<video id="remote-video" autoplay playsinline></video>`

Were you able to test that already? I can't test it myself :/

**Comment by ianramzy** [comment]
Basic Android and Safari on iOS support is complete. Detecting unsupported browsers still needs to be addressed properly, see #18 for more details.

**Comment by inglesuniversal** [comment]
ianramzy ---> Test was just made between an iPhone 8 and a MacBook Air ....

PASSED with Flying Colors!!!


CONGRATULATIONS for such a darn quick update!!!!

**Comment by inglesuniversal** [comment]
I'm quite new to node.js 

Now that I have it running on my local machine

How can I build this app so it works on a serverless HTML enabled bucket?

**Comment by Chaphasilor** [comment]
This doesn't work without a server ^^

You need a backend in order for the clients to find each other and for managing the calls, etc.
There's also a second backend used (twilio), which is a TURN server, so it helps with the peer-to-peer connections and can also act as a video relay if p-t-p doesn't work for some reason.

If you want to host it yourself, you should use a free service like Heroku (that's also where zipcall.io is hosted) and you also need a (free) twilio account. Twilio won't stay free for long though, it depends on your usage

**Comment by inglesuniversal** [comment]
Thanks for your advice... actually I tried Heroku but my account will take about a week to activated again.

However, I can spin up a Node.js server (bitnami) if you can kindly point me to a blog that would show me the steps to set up something like this.

My background is more into the "dark ages" of PHP and MySQL... So, I'm eager to learn new stuff.

Thanks for your amazing work and valuable time answering these basic questions.

Stay Safe!

**Comment by Chaphasilor** [comment]
If you have a server environment available where `node` and `npm` are installed, you just clone the server, run `npm install` to download the dependencies, add your twilio tokens to a `.env` file as `LOCAL_TWILLIO_SID=<your sid>` and `LOCAL_AUTH_TOKEN=<your auth token>` and then start the server with `node server.js` or `npm start`. After that, you server should be running on port `3000`, which you can customize by providing the `PORT=<your desired port>` variable inside the `.env` file. Then you just go to `<your server address>:<your port>` and should see the zipcall landing page.

**Comment by inglesuniversal** [comment]
Thanks... You have been amazing... providing this phenomenal guidance.

Just one last question:

Can the port be set to 80 and can you have several node applications running at the same time?

I run an education service online... So I guess I can provide more fresh ideas to spice up your project in the coming months.

Thanks again.

**Comment by ianramzy** [comment]
Yes, you should be able to run multiple node servers on multiple ports at once. If you have more questions you can ask them on Gitter (link in readme). This is not the place for it :)

**Comment by Chaphasilor** [comment]
> Can the port be set to 80 and can you have several node applications running at the same time?

Sure, there's no limit to the number of node instances. If you have a server bound to a port, you'll have to make sure no other service is listening on that port as well though. So if your server's port `80` is not in use, you can set that as the port.

Also, you'll need to add an ssl certificate for the server to use, because WebRTC, specifically accessing the user's camera and mic, requires a secure context.  
Setting this up shouldn't be too hard, maybe try searching for `express letsencrypt certificate`?

**Comment by inglesuniversal** [comment]
Hi: I followed your advice and I started a node server, installed the script, but I think my build in not set up correctly...

I'm getting this page with and empty text screen:

https://myserver.com/decentralized-video-chat/public/jointest

I had to manually type the .HTML extension so that the file would actually be visible pages (landingpage / newcall.html) without any port shown as part of the the URL

Once I pick my nick to start the video chat I got another blank page with this:

https://myserver.com/decentralized-video-chat/public/jointest


PS: Please allow me to apologize since I quite new into node.js

Regards
