### ISSUE TITLE
Privacy and tracking

### ISSUE THREAD

**Issue by hialvaro** [ianramzy/decentralized-video-chat#8]
First I'd like to say that your project is awesome. It works pretty well and I'm really glad and thankful you have chosen to go Open Source with it. As you say on your web page (and it's something I really love) "_Zipcall is built privacy first._" and I've seen some things that could be improved about it. 

First it would be good also to remove the Google Analytics from the site. If you still want to use analytics you could use some privacy-friendly analytics like [Maotomo](https://matomo.org/), [Ackee](https://ackee.electerious.com/) or [Open Web Analytics](http://www.openwebanalytics.com/) or just using none of them at all.

Secondly, I see that you're using Twilio to get ephemeral credentials to use the TURN server. I don't think this really compromises the user privacy in any way, but I think it would be great, from a self hosting perspective, to find an alternative (it would be great if it didn't depend on a 3rd party) to do what Twilio is doing. In order to register there (I was trying to set up Zipcall locally) I need to give my phone number and that's a thing that I and maybe other users who are interested aren't willing to do. I would love to see different Zipcall instances working on the internet, this would be really great, so making thins easy for self hosting is a nice thing.

And lastly, it would be good to locally host the fonts you're getting from Google Fonts as there are some concerns about getting them via their API, you can [read more here](https://webmasters.stackexchange.com/a/60470). I'd say the same with jQuery but I understand doing it the way you're doing it.

As I've said these are just some concerns I've seen, but it's nothing to really worry about. Your project is beautiful and works really well! Congratulations on this nice work you've done so far!!

**Comment by ianramzy** [comment]
Awesome feedback! I will look into other analytics providers, but for now, I think google analytics is very valuable. I will look into Twillio and TURN improvements. I'm pretty swamped right now so this isn't my main priority, but I'm very happy you brought it up!

**Comment by Chaphasilor** [comment]
[coturn](https://github.com/coturn/coturn) is an open-source TURN server implementation. We should try out how hard it is to use that instead of twilio, and if it's easy enough, we could put up some instructions on how to use zipcall with coturn and self-host both :)

**Comment by mcginty** [comment]
On that note, the marketing blurb on the site:
```
Calls are entirely between you and your caller,
decentralized from any server. Call data never
leaves the browser. Cool right?
```

is misleading as long as you support TURN servers instead of just STUN.

**Comment by Chaphasilor** [comment]
yeah, there are some sketchy wordings throughout the site @ianramzy...

**Comment by leeoniya** [comment]
in related news

https://news.ycombinator.com/item?id=22855407

**Comment by kenokenobingo** [comment]
+1 for removing _all_ trackers.

**Comment by hialvaro** [comment]
Awesome! Thanks for removing GAnalitycs and Ads!!!!

**Comment by ianramzy** [comment]
I only removed GAds, Analytics is still there, and will remain for the foreseeable future. Sorry for any frustration this may cause.

**Comment by mcginty** [comment]
@ianramzy in that case, you should change the buzzwords on the main page to reflect the truth of the current service offered.

**Comment by hialvaro** [comment]
Yes, the part of "Zipcall is built privacy first." should be changed.
